# Udemy Course: Python for Data Science

	Intro:
    - Guido van Russom - 1991  : Python founded
	- Interpreted not complied-- code does not need to be converted to machine language- smaller codes
    - Current version: python3![image.png]
        
        	- Python idle-- integrated development environment
	- Jupyter Notebooks-- web based interface-- .ipynb extension-- cell based structure
	- Anaconda-- bundle which has libraries, ide, python-- all in one

Input/OP

In [1]:
#O/P
print("Welcome")

Welcome


In [2]:
#I/P
cost=input("Enter the cost of each item: ")
print("The cost of each item is : ", cost)

Enter the cost of each item: 150
The cost of each item is :  150


Working with Different Datatypes

There are two types of data in python:

- Primitive(Datatype) -- most basic data structures-- 
  int , float, string, bool
  
  
- Non Primitive-- non basic--
  list, tuples, dictionaries
  
 Datatype vs DataStructure
 
 Datatype     -- Describe the type of data which can be stored-- usually assigned against a single element
 DataStructure-- Collections in which data can be stored

Variables--

Python is a dynamically typed language-- variables are allocated their respective data types in runtime. 

This is the reason why we need nit define the variable types and we can directly assign the variable values.

Rules:
Start- letters and underscore only
Overall- no special characters , spaces



Arithematic Operators:

Division:  / corresponds float division
           // corresponds integer division
           %- modulo
           
Comparision operators: 

 == returns Boolean true false
 != is not equal to
 
 Conditional statements:
 
 if-- only one 
 else-- only one-- requires an if 
 elif-- can be multiple -- requires an if statement
 
 Loops:
 for loop in python runs with range function and takes three inputs-- start, stop and step value
 The loop however runs only till stop-1 iterations

In [3]:
for i in range (1,10,1):
    Mul_Of_Two=2 * i
    print(Mul_Of_Two)

2
4
6
8
10
12
14
16
18


Observe that only till 2*9=18 is printed even though we mentioned 10 as the stop value. That is because the loop iterates only till stop-1 iterations


In [4]:
#Task: Print 0 to 20 even numbers using sum
start=0
for i in range(0,21,2):
    eve=start+i
    print(eve)

0
2
4
6
8
10
12
14
16
18
20


While Loops:  takes in a condition and runs until the condition is true

i=1
while i<10:
    print(i)
    i=i+1
    
    #Beware of control statement and dont run into infinite loop. 

In [8]:
while True:
    username=input("Enter User Name")
    if username=="Shantanu":
        print("Welcome Shantanu")
        break
    else:
     print(" Wrong user name")

Enter User NameHaris
 Wrong user name
Enter User NameShantanu
Welcome Shantanu


Sequences-- built in in python -- ordered collection of objects-- lists tuple dictionaries

Lists:-- Mutable-- can be modified-- elements may or maynot be of same datatype
    Use indexing to extract individual elements, len() to find length, slice the list using list[inclusive, exclusive]

In [9]:
list1=["a", 10, "hello"]
list1[0:1]

['a']

In [10]:
list1[-1]

'hello'

In [13]:
#last two elements 
#3 is exluded, 3-1=2
list1[1:3]

[10, 'hello']

In [15]:
for i in list1:
    print(i)

a
10
hello


Dictionaries--- Mutable-- storage in key value pairs

In [17]:
dict1={"Name":"Shantanu", "Age": 26, "Sex": "M"}

In [18]:
print(dict1.keys())

dict_keys(['Name', 'Age', 'Sex'])


In [19]:
print(dict1.values())

dict_values(['Shantanu', 26, 'M'])


In [20]:
dict1["Age"]

26

In [21]:
for i in dict1:
    print(dict1[i])

Shantanu
26
M


Tuples: IMMUTABLE-- different from list as they cant be modified

In [23]:
tuple1=(5,"red")
for i in tuple1:
    print(i)
    

5
red


All the methods applicable to lists are applicable to tuples.

Functions-- built in functions, self declared functions
Built in functions: https://docs.python.org/3/library/functions.html


In [27]:
# We can also create our own functions
def add1(x,y):
    sum=x+y
    return sum

final=add1(6,7)
print(final)

13


# Libraries for Data Science

In [2]:
import pandas as pd
import numpy as np
import sklearn as skt
import matplotlib.pyplot as plt

Pandas: Storing , accesing, cleaning and exploring data.

Provides 2 data structures: Series(1-D data structure) and Dataframe(2-D data structure)

Numpy: Numerical python 

Data can be structured into 1D, 2D, 3D Numpy arrays.

Numpy provides mathematical computational functions on these arrays.


Some of the functionalities of pandas is derived from pandas

Pandas vs Numpy-- pandas is used for data manipulation whereas numpy is used for mathematical computations.

Matplotlib: for visualization

Seaborn: Built on top of matplotlib-- provides additional graph options with lesser coding

# Numpy 

Numpy Array

Grid of values
Example:[0 1 2 3
        5 2 4 1]

Multidimensional data structure

Called as nd array

Dimension of a numpy array can be calculated using .ndim.

Numpy Array vs Python List:
- More flexibility in numpy arrays-- more functions applicable
- More efficient- less memory more space
- Help in handling huge multidimensional data sets

# Creating Numpy Arrays

In [1]:
import numpy as np

In [2]:
arr1=np.array([0,8,0,9])
print(arr1)

[0 8 0 9]


In [3]:
arr2=np.array((0,8,0,9))
print(arr2)

[0 8 0 9]


List or Tuple is passed in array function inside the numpy library

In [4]:
print(arr2.ndim)

1


In [5]:
arr3=np.array([[1,2,4],[7,8,9]])
print(arr3)

[[1 2 4]
 [7 8 9]]


In [6]:
print(arr3.ndim)

2


In [8]:
arr4=np.array([[[1,2,4],[7,8,9],[5,9,8]]])
print(arr4)

[[[1 2 4]
  [7 8 9]
  [5 9 8]]]


In [9]:
print(arr4.ndim)

3


# Indexing a Numpy Array

In [10]:
arr3=np.array([[1,2,4],[7,8,9]])
print(arr3)

[[1 2 4]
 [7 8 9]]


In [11]:
print(arr3[1])

[7 8 9]


In [12]:
print(arr3[1][1])

8


In [23]:
arr4=np.array([[[1,2,4]],[[7,8,9]],[[5,9,8]]])
print(arr4)

[[[1 2 4]]

 [[7 8 9]]

 [[5 9 8]]]


In [25]:
print(arr4[0][0])

[1 2 4]


In [26]:
print(arr4.shape)

(3, 1, 3)


# Iterating over 1-D Numpy Array

In [3]:
arr45=np.array([56, 85,282])
print(arr45)

[ 56  85 282]


In [4]:
for i in arr45:
    print(i)

56
85
282


# Iterating over 2-D Numpy Array

In [8]:
arr2_D=np.array([[56, 85,245],[282,65,889]])
print(arr2_D)
print(arr2_D.shape)

[[ 56  85 245]
 [282  65 889]]
(2, 3)


In [9]:
for i in arr2_D:
    print(i)
    

[ 56  85 245]
[282  65 889]


In [10]:
for i in arr2_D:
    for j in i:
        print(j)

56
85
245
282
65
889


In [ ]:
# Iterating over 2-D Numpy Array